package edu.kit.ifv.populationsynthesis.rules.composer

import edu.kit.ifv.populationsynthesis.rules.Rule

/**
 * A rule composer takes a target area, a way to generate rules for any given area, and produces a list of rules that
 * are composed from a logic.
 *
 * One aspect will be the hierarchic rule composition. Where a target area has associated child areas, and the rules
 * for the target are generated by adding the sum of targets of the child areas.
 *
 * This is the highest interface, and the concrete structure of rule derivation is not preset.
 */
fun interface RuleComposer<AREA, H> {
    fun compose(target: AREA, rulesFor: (AREA) -> Collection<Rule<H>>): List<Rule<H>>
}